name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make CodeIntel better? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the pain point or use case
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
      placeholder: Other ways to solve this

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part would this affect?
      options:
        - MCP Tools
        - Search & Indexing
        - Dependency Analysis
        - Code Style Analysis
        - Frontend UI
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in implementing this?
      options:
        - label: I'd like to work on this feature
